# Minecraft 1.21.4
minecraft_version=1.21.4
java_target=21
mixin_compat=JAVA_21
fabric_minecraft_dependency=>=1.21.4 <1.21.5
neoforge_minecraft_range=[1.21.4,1.21.5)
fabric_version=0.119.4+1.21.4
neoforge_version=21.4.158
neoforge_range=[21.4,21.5)
cloth_config_version=17.0.144
cloth_config_min=17.0.0
modmenu_version=13.0.4
modmenu_min=13.0.0
placeholder_api_version=2.5.2+1.21.3
