# Minecraft 26.2
minecraft_version=26.2
java_target=25
mixin_compat=JAVA_25
fabric_minecraft_dependency=>=26.2 <26.3
neoforge_minecraft_range=[26.2,26.3)
fabric_version=0.161.0+26.2
neoforge_version=26.2.0.88
neoforge_range=[26.2,26.3)
cloth_config_version=26.2.155
cloth_config_min=26.2.155
modmenu_version=20.0.3
modmenu_min=20.0.0
placeholder_api_version=3.1.0-beta.1+26.2
