# Minecraft 26.3
minecraft_version=26.3
java_target=25
mixin_compat=JAVA_25
fabric_minecraft_dependency=>=26.3 <26.4
neoforge_minecraft_range=[26.3,26.4)
fabric_version=0.161.0+26.3
neoforge_version=26.3.0.48-beta
neoforge_range=[26.3,26.4)
cloth_config_version=26.3.159
cloth_config_min=26.3.159
modmenu_version=21.0.0
modmenu_min=21.0.0
placeholder_api_version=3.2.0+26.3
